MyBookShop/Controllers/BookController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyBookShop_DataAccess;
using MyBookShop_DataAccess.Repository.IRepository;
using MyBookShop_Models;
using MyBookShop_Models.Models;
using MyBookShop_Models.VIewModel;
using MyBookShop_Utility;
using NuGet.ContentModel;
using System.Security.Cryptography;

namespace MyBookShop.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookRepository _bookRep;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public BookController(IBookRepository bookRep, IWebHostEnvironment webHostEnvironment)
        {
            _bookRep = bookRep;
            _webHostEnvironment = webHostEnvironment;
        }


        public IActionResult Index()
        {
            IEnumerable<Book> objList = _bookRep.GetAll(includeProperty:$"{WC.AuthorName},{WC.GenreName}");

            return View(objList);
        }

        public IActionResult Upsert(int? id)
        {
            VMBook VMBook = new VMBook()
            {
                Book = new Book(),
                AuthorSelectList = _bookRep.GetDropDownList(WC.AuthorName),
                GenreSelectList = _bookRep.GetDropDownList(WC.GenreName)
            };

            if (id != null)                       
            {
                VMBook.Book= _bookRep.Find(id.GetValueOrDefault());
                if (VMBook.Book==null) return NotFound();
            } 
            return View(VMBook);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Upsert(VMBook BookVM)              
        {
            var files = HttpContext.Request.Form.Files;             //возвращает список файлов которые мы выбрали
            string upload = _webHostEnvironment.WebRootPath + WC.ImagePath; //собирается полный путь до папки гду будут хранитья картинки
            string fileName = Guid.NewGuid().ToString(); //делаем уникальное имя
            if (BookVM.Book.BookId == 0)
            {

                string extension = Path.GetExtension(files[0].FileName);  
                using (var fileStream = new FileStream(Path.Combine(upload, fileName + extension), FileMode.Create))
                {
                    files[0].CopyTo(fileStream);  
                }

                BookVM.Book.Image = fileName + extension; //добавляем ссылку на файл

                _bookRep.Add(BookVM.Book);             //добавляем данный в дбконтекст
                TempData[WC.Success] = "Данные по книге успешно добавлены";
            }
            else //нужно обновить объект
            {
                var objfromDB = _bookRep.FirstOfDefault(u => u.BookId == BookVM.Book.BookId , isTracking: false);
                if (files.Count > 0)
                {
                  //  string upload = webRootPath + WC.ImagePath;
                //    string fileName = Guid.NewGuid().ToString(); //делаем уникальное имя
                    string extension = Path.GetExtension(files[0].FileName);   //получаем тип файла
                    var oldFile = Path.Combine(upload, objfromDB.Image);
                    if (System.IO.File.Exists(oldFile))
                    {
                        System.IO.File.Delete(oldFile);
                    }


                    using (var fileStream = new FileStream(Path.Combine(upload, fileName + extension), FileMode.Create))
                    {
                        files[0].CopyTo(fileStream);  //копируем файл
                    }
                    BookVM.Book.Image = fileName + extension;

                }
                else
                {
                    BookVM.Book.Image = objfromDB.Image;
                }
                TempData[WC.Success] = "Данные по книге успешно обновлены";
                _bookRep.Update(BookVM.Book);

            }
            _bookRep.Save();

            return RedirectToAction("Index");          // переходим на метод индекс чтобы вернуться на экран с категориями

            //}
            BookVM.AuthorSelectList = _bookRep.GetDropDownList(WC.AuthorName);
          BookVM.GenreSelectList = _bookRep.GetDropDownList(WC.GenreName);
            return View(BookVM); ;          // переходим на метод индекс чтобы вернуться на экран с категориями
        }



        //GET - DELETE
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
       //     Product product = _ProdRep.FirstODefault(u => u.Id == id, includeProperty: "Category,ApplicationType");
            var obj = _bookRep.FirstOfDefault(u => u.BookId == id, includeProperty: $"{WC.AuthorName},{WC.GenreName}");
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }
        //POST - DELETE
        [HttpPost,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _bookRep.Find(id.GetValueOrDefault());
            if (obj == null)
            {
                return NotFound();
            }
            _bookRep.Remove(obj);
            TempData[WC.Success] = "Данные по книге удалены";
            _bookRep.Save();
            return RedirectToAction("Index");


        }




    }
}

MyBookShop/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using MyBookShop_DataAccess.Repository.IRepository;
using MyBookShop_Models;
using MyBookShop_Models.Models;
using MyBookShop_Models.Models.VIewModel;
using MyBookShop_Models.VIewModel;
using MyBookShop_Utility;
using System.Security.Claims;
using System.Text;

namespace MyBookShop.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly IBookRepository _bookRepo;
        private readonly IApplicationUserRepository _appUserRepo;
        private readonly IOrderDetailsRepository _orderDetailsRepo;
        private readonly IOrderHeaderRepository _orderHeaderRepo;


        private readonly IWebHostEnvironment webHostEnvironment;
        private readonly IEmailSender _emailSender;
        public CartController(IBookRepository bookRepo, IWebHostEnvironment webHostEnvironment, IEmailSender emailSender
            , IApplicationUserRepository appUserRepo
            , IOrderDetailsRepository orderDetailsRepo
            , IOrderHeaderRepository orderHeaderRepo)
        {
            _bookRepo=bookRepo ;
            _appUserRepo=appUserRepo ;
            _orderDetailsRepo=orderDetailsRepo ;
            _orderHeaderRepo=orderHeaderRepo ;
            this.webHostEnvironment = webHostEnvironment;
            _emailSender = emailSender;
              
        } 

        public IActionResult Index()
        {
            List<ShopingCart> shopingCartList = FindProductIncart();
            List<int> prodInCart = shopingCartList.Select(x => x.BookId).ToList();

            var Book = _bookRepo.GetAll(includeProperty:$"{WC.GenreName},{WC.AuthorName}");

            List<Book> productList = Book.Where(u => prodInCart.Contains(u.BookId)).ToList();
            return View(productList);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Index")]
        public IActionResult IndexPost(IEnumerable<Book> books)
        {
            List<ShopingCart> shopingCartslist = new List<ShopingCart>();
            foreach (Book book in books)
            {
                shopingCartslist.Add(new ShopingCart() { BookId = book.BookId });
            }
            HttpContext.Session.Set(WC.SessionCart, shopingCartslist);
            return RedirectToAction(nameof(Summary));
        }


        public IActionResult Summary()
        {
            ApplicationUser applcationUser;
            int tempId= 0;
            if (User.IsInRole(WC.AdminRole))
            {
                if (HttpContext.Session.Get<int>(WC.SessionOrderId) != 0)
                {
                    OrderHeader orderHeader1 = _orderHeaderRepo.FirstOfDefault(u => u.Id == HttpContext.Session.Get<int>(WC.SessionOrderId));
                    applcationUser = new ApplicationUser()
                    {
                        Email = orderHeader1.Email,
                        PhoneNumber = orderHeader1.PhoneNumber,
                        FullName = orderHeader1.FullName,
                        City = orderHeader1.City,
                        StreetAddress= orderHeader1.StreetAddress,
                        Region = orderHeader1.Region,
                       
                    };
                    tempId= orderHeader1.Id;
                }
                else
                {
                    applcationUser = new ApplicationUser();
                }
            }
            else
            {
                //Первый способ
                var claimsIdentity = (ClaimsIdentity)User.Identity;
                var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
                applcationUser = _appUserRepo.FirstOfDefault(x => x.Id == claim.Value);
            }

            var userID = User.FindFirstValue(ClaimTypes.NameIdentifier);
            List<ShopingCart> shopingCartList = FindProductIncart();
            List<int> prodInCart = shopingCartList.Select(x => x.BookId).ToList();
            IEnumerable<Book> bookList = _bookRepo.GetAll(u => prodInCart.Contains(u.BookId), includeProperty:WC.AuthorName);
            BookUserVM BookUserVM = new BookUserVM()
            {
                ApplicationUser = applcationUser,//_appUserRepo.FirstOfDefault (x => x.Id == userID),
                BookList = bookList.ToList(),
                tempid=tempId
            };
            return View(BookUserVM); ;
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Summary")] 
        public async Task<IActionResult> SummaryPost(BookUserVM BookUserVM)
        {
            OrderHeader orderHeader;
          if (BookUserVM.tempid==0)
            await SendEmailOrder(BookUserVM);

            var userID = User.FindFirstValue(ClaimTypes.NameIdentifier);

            if (BookUserVM.tempid != 0)
            {
                orderHeader = _orderHeaderRepo.FirstOfDefault(x => x.Id == BookUserVM.tempid);
                orderHeader.FinalOrderTotal = BookUserVM.BookList.Sum(x => x.Price);
                orderHeader.OrderStatus = WC.StatusInProcess;
                _orderHeaderRepo.Update(orderHeader);
            } else
            {
                orderHeader = new OrderHeader()
                {
                    ApplicationUserId = userID
                     ,FullName = BookUserVM.ApplicationUser.FullName
                     , Email = BookUserVM.ApplicationUser.Email
                     , PhoneNumber = BookUserVM.ApplicationUser.PhoneNumber
                     , City = BookUserVM.ApplicationUser.City
                     ,Region = BookUserVM.ApplicationUser.Region
                     , StreetAddress = BookUserVM.ApplicationUser.StreetAddress
                     , DateStartState = DateTime.Now
                     , OrderStatus = WC.StatusPending
                     ,FinalOrderTotal = BookUserVM.BookList.Sum(x => x.Price)
                };

                _orderHeaderRepo.Add(orderHeader);

            }

            _orderHeaderRepo.Save();


            //  var Book = _bookRepo.GetAll(includeProperty: $"{WC.GenreName},{WC.AuthorName}");
            if (BookUserVM.tempid != 0)
            {
                var OrderDeatails2 = _orderDetailsRepo.GetAll(x => x.OrderHeaderId == BookUserVM.tempid);
                foreach (var order in OrderDeatails2)
                {
                    var bookedit = _bookRepo.FirstOfDefault(x => x.BookId == order.BookId, includeProperty: $"{WC.GenreName},{WC.AuthorName}");
                    bookedit.Amount++;
                    _bookRepo.Update(bookedit);
                    
                }
                _orderDetailsRepo.RemoveRange(OrderDeatails2);

            }
            
                foreach (var book in BookUserVM.BookList)
                {
                    OrderDetails OrderDeatails = new OrderDetails()
                    {
                        OrderHeaderId = orderHeader.Id,
                        BookId = book.BookId
                    };
                    var bookedit = _bookRepo.FirstOfDefault(x => x.BookId == book.BookId, includeProperty: $"{WC.GenreName},{WC.AuthorName}");
                    bookedit.Amount--;
                    _bookRepo.Update(bookedit);
                    _orderDetailsRepo.Add(OrderDeatails);
                }
                _orderDetailsRepo.Save();
                _bookRepo.Save();
            

             

            return RedirectToAction(nameof(InquaryConfirmation)); ;
        }









        private async Task SendEmailOrder(BookUserVM BookUserVM)
        {
            var pathtoTemplate = webHostEnvironment.WebRootPath
                            + Path.DirectorySeparatorChar.ToString()
                            + "templates" 
                            + Path.DirectorySeparatorChar.ToString() 
                            + "Inquiry.html";
            var subject = "new Inquiry";
            string HtmlBody = "";
            using (StreamReader sr = System.IO.File.OpenText(pathtoTemplate))
            {
                HtmlBody = sr.ReadToEnd();
            }
            StringBuilder productListSB = new StringBuilder();
            foreach (var book in BookUserVM.BookList)
            {
                productListSB.Append($"-  Название:{book.Title} <span style='font-size:14px;'> Автор: {book.Author.NameAuthor}</span><br/>");
            }

            string messageBody = string.Format(HtmlBody,
                BookUserVM.ApplicationUser.FullName,
                BookUserVM.ApplicationUser.Email,
                BookUserVM.ApplicationUser.PhoneNumber,
                BookUserVM.ApplicationUser.City,
                productListSB.ToString()
                );
            await _emailSender.SendEmailAsync(WC.AdminEmail, subject, messageBody);
        }

        public IActionResult InquaryConfirmation()
        {


            HttpContext.Session.Clear();
            return View(); ;
        }



        public IActionResult Remove(int id)
        {
            List<ShopingCart> shopingCartList = FindProductIncart();
            shopingCartList.Remove(shopingCartList.FirstOrDefault(x => x.BookId == id));
            TempData[WC.Success] = "Книга удалена из корзины";
            HttpContext.Session.Set(WC.SessionCart, shopingCartList);
            return RedirectToAction(nameof(Index));
        }



        public List<ShopingCart> FindProductIncart()
        {
            if (HttpContext.Session.Get<IEnumerable<ShopingCart>>(WC.SessionCart) != null &&
                            HttpContext.Session.Get<IEnumerable<ShopingCart>>(WC.SessionCart).Count() > 0)
            {
                return HttpContext.Session.Get<List<ShopingCart>>(WC.SessionCart);
            }
            return new List<ShopingCart>();
        }
    }
}

MyBookShop/Controllers/GenreController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyBookShop_DataAccess;
using MyBookShop_DataAccess.Repository.IRepository;
using MyBookShop_Models;
using MyBookShop_Models.Models;
using System.Security.Cryptography;

namespace MyBookShop.Controllers
{
    public class GenreController : Controller
    {
        private readonly IGenreRepository _genreRep;
        public GenreController(IGenreRepository genreRep)
        {
            _genreRep = genreRep;
        }


        public IActionResult Index()
        {
            IEnumerable<Genre> objList = _genreRep.GetAll();

            return View(objList);
        }

        public IActionResult Upsert(int? id)
        {
            Genre genre = new Genre();
            if (id != null)                       
            {
                genre = _genreRep.Find(id.GetValueOrDefault());         
                if (genre == null)
                {
                    return NotFound();
                }
                return View(genre);              
            }
            return View(genre);


        }

        [HttpPost,ActionName("Upsert")]
        [ValidateAntiForgeryToken]
        public IActionResult UpsertPost(Genre obj)          
        {
            if (obj.GenreId == 0)
            {
                _genreRep.Add(obj);                
                _genreRep.Save();                
                return RedirectToAction("Index");

            }
            else
            {
                _genreRep.Update(obj);             
                _genreRep.Save();                
                return RedirectToAction("Index");

            }


            return View(); ;        
        }



        //GET - DELETE
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _genreRep.Find(id.GetValueOrDefault());
            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }
        //POST - DELETE
        [HttpPost,ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _genreRep.Find(id.GetValueOrDefault());
            if (obj == null)
            {
                return NotFound();
            }
            _genreRep.Remove(obj);
            _genreRep.Save();
            return RedirectToAction("Index");


        }




    }
}

MyBookShop/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@using MyBookShop_Utility

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyProject.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/fontawesome/css/all.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.css" integrity="sha256-He3QEBKoL/nMXlVsoM7S2C2kjFQqS5L+mgA+F8LpG+U=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdn.syncfusion.com/ej2/material.css" />
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
    <link href="~/lib/jquery-ui-1.13.2.custom/jquery-ui.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="" asp-controller="Home" asp-action="Index">
                    <img     src="~/Images/Books2.png" width="100%"/>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                   
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole(WC.AdminRole))
                        {
                        <li class="nav-item dropdown">
                            <a class="nav-link  dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Данные по складу
                            </a>

                            <ul class="dropdown-menu">
                                <a class="dropdown-item " asp-area="" asp-controller="Author" asp-action="Index">Автор</a>
                                <a class="dropdown-item " asp-area="" asp-controller="Genre" asp-action="Index">Жанр</a>
                                <a class="dropdown-item " asp-area="" asp-controller="Book" asp-action="Index">Книги</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item " asp-area="Identity" asp-page="/Account/Register">Создать админа</a>
                            </ul>
                        </li>
                       
                            <li class="nav-item dropdown">
                                <a class="nav-link  dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Данные заказа
                                </a>
                                <ul class="dropdown-menu">
                                    <a class="dropdown-item " asp-area="" asp-controller="Order" asp-action="Index">Текущие заказы</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="HistOrder" asp-action="index">История заказов</a>
                                </ul>
                            </li>
                        }
                     


                        <li>
                            @if (HttpContextAccessor.HttpContext.Session.Get<List<ShopingCart>>(WC.SessionCart) != null)
                            {
                                <a asp-action="Index" asp-controller="Cart" class="nav-link">
                                    @{
                                        var count = HttpContextAccessor.HttpContext.Session.Get<List<ShopingCart>>(WC.SessionCart).Count();
                                    }
                                    <i class="fas fa-shopping-cart"></i>  (@count)
                                </a>
                            }
                            else
                            {
                                <a href="#" class="nav-link">
                                    <i class="fas fa-shopping-cart"></i>  (0)
                                </a>
                            }
                        </li>
                        
                    </ul>
                    <partial name="_LoginPartial" class="text-end" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notifocations" />
            @RenderBody()
           
        </main>
    </div>

    <footer class="border-top bg-dark footer text-muted">
        <div class="container">
            &copy; 2022 - MyBookShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.syncfusion.com/ej2/dist/ej2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
<script src="~/lib/jquery-ui-1.13.2.custom/jquery-ui.min.js"></script>
     @await RenderSectionAsync("Scripts", required: false)
    <ejs-scripts></ejs-scripts>
</body>
</html>

MyBookShop/Views/Shared/_Notifocations.cshtml
@using MyBookShop_Utility


@if (TempData[WC.Success] !=null){
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData[WC.Success]');
    </script>
}

@if (TempData[WC.Error] !=null){
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData[WC.Error]');
    </script>
}

MyBookShop/Views/Shared/_individualBookCard.cshtml
@using MyBookShop_Utility
@model MyBookShop_Models.Models.Book

<div class="col-lg-4 col-md-6 pb-4 filter @Model.Genre.NameGenre.Replace(' ','_')">
    <!-- Card-->
    <div class="g" style="border:1px solid #222">
            <div class="form-group row">
                <div class="col-5" >
                    <img class="m-2 " width="135px" height="210px" src="@WC.ImagePath@Model.Image" alt="Card image cap">
                </div>
            
                <div class="card-body px-3 pt-3 col-4 pb-1">
                    <div class=""><label class="h6">@Model.Title</label></div>
                    <div class=""><label><span class="text-primary h5">@Model.Author.NameAuthor</span> </label> </div>
                    <div class="dropdown-divider"></div>
                    <div class=""><label><span class="h6">@Model.ShortDesc</span> </label> </div>
                </div>
            </div>
     
             <div class ="card-body p-1 px-3 row">
                            <div class="col-6">
                                <span class="badge p-2 border w-100" style="background-color:lavenderblush; color:black">@Model.Genre.NameGenre</span>
                            </div>
                         <div class="col-6 border-0">
                            @if (Model.Amount > 0)
                              {
                                   <span class="badge p-2 border w-100" style="background-color:aliceblue; color:black">Цена @Model.Price Р.</span>
                             } else
                             {
                    <span class="badge p-2 border w-100" style="background-color:yellowgreen; color:black">Нет в наличии</span>
                             }
             
                         </div>
                        <div class="col-12 p-1">
                         <a asp-action="Details" asp-route-id="@Model.BookId" class="btn btn-dark form-control btn-sm p-2" style="height:40px">Подробности</a>
                        </div>
             </div>
    </div>
</div>